services:
  web:
    container_name: pc_web
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/web:cached
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DB_HOST: db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: project_cnab_development
      SELENIUM_REMOTE_URL: "http://selenium:4444/wd/hub"
    develop:
      watch:
        - action: rebuild
          path: .
    stdin_open: true
    tty: true
    networks:
      - pc_network

  db:
    container_name: pc_db
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: project_cnab_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pc_network

  selenium:
    container_name: pc_selenium
    image: selenium/standalone-chromium:latest
    shm_size: 2g
    ports:
      - "4444:4444"
      - "5900:5900"
      - "7900:7900"
    networks:
      - pc_network

networks:
  pc_network:

volumes:
  bundle_cache:
  postgres_data:
