---
openapi: 3.0.1
info:
  title: API CNAB
  version: v1
paths:
  "/api/transactions":
    get:
      summary: Lista todas as transações com paginação e filtro por loja
      tags:
      - Transações
      parameters:
      - name: page
        in: query
        description: 'Número da página (default: 1)'
        schema:
          type: integer
      - name: store_id
        in: query
        description: Filtrar por loja específica
        schema:
          type: integer
      responses:
        '200':
          description: Transações listadas
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            date:
                              type: string
                              format: date
                            transaction_type:
                              type: string
                            value:
                              type: integer
                            formatted_value:
                              type: string
                            cpf:
                              type: string
                            card:
                              type: string
                            hour:
                              type: string
                        relationships:
                          type: object
                          properties:
                            store:
                              type: object
                              properties:
                                data:
                                  type: object
                                  properties:
                                    id:
                                      type: string
                                    type:
                                      type: string
                  included:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            owner:
                              type: string
                  pagination:
                    type: object
                    properties:
                      count:
                        type: integer
                      page:
                        type: integer
                      pages:
                        type: integer
                      next:
                        types:
                        - integer
                        -
                      prev:
                        types:
                        - integer
                        -
  "/api/transactions/{id}":
    get:
      summary: Mostra uma transação específica
      tags:
      - Transações
      parameters:
      - name: id
        in: path
        description: ID da transação
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Transação encontrada
          content:
            application/vnd.api+json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        properties:
                          date:
                            type: string
                            format: date
                          transaction_type:
                            type: string
                          value:
                            type: integer
                          formatted_value:
                            type: string
                          cpf:
                            type: string
                          card:
                            type: string
                          hour:
                            type: string
                      relationships:
                        type: object
                        properties:
                          store:
                            type: object
                            properties:
                              data:
                                type: object
                                properties:
                                  id:
                                    type: string
                                  type:
                                    type: string
                  included:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        type:
                          type: string
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
                            owner:
                              type: string
        '404':
          description: Transação não encontrada
servers:
- url: http://0.0.0.0:3000
  description: Servidor Local
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
